drop table FILMS_SALLES;
drop table SALLESCINEMA;

CREATE TABLE SALLESCINEMA (
		IdS VARCHAR2(4) CONSTRAINT pk_sallescinema PRIMARY KEY,
		NOM VARCHAR2(100),
		VILLE VARCHAR2(50)
);

CREATE TABLE FILMS_SALLES (
        IdS VARCHAR2(4) CONSTRAINT fk_films_sallessallescinema REFERENCES SALLESCINEMA(IdS),
        IdF VARCHAR2(4) CONSTRAINT fkfilms_salleslesfilms REFERENCES LESFILMS(IdF),
		--contrainte table
        CONSTRAINT pkfilms_salles PRIMARY KEY (IdS, IdF)
);

INSERT INTO SALLESCINEMA VALUES ('1', 'La Bretagne', 'Quimper');
INSERT INTO SALLESCINEMA VALUES ('2', 'Studio', 'Quimper');
INSERT INTO SALLESCINEMA VALUES ('3', 'Les Arcades', 'Quimper');
INSERT INTO SALLESCINEMA VALUES ('4', 'Cinemarine', 'Benodet');
INSERT INTO SALLESCINEMA VALUES ('5', 'Le Dauphin', 'Plougonvelin');
INSERT INTO SALLESCINEMA VALUES ('6', 'Cineville', 'Lorient');
INSERT INTO SALLESCINEMA VALUES ('7', 'Garenne', 'Vannes');
INSERT INTO SALLESCINEMA VALUES ('8', 'Les Arcades', 'Auray');
INSERT INTO SALLESCINEMA VALUES ('9', 'Celtic', 'Brest');
INSERT INTO SALLESCINEMA VALUES ('10', 'Studios', 'Brest');
INSERT INTO SALLESCINEMA VALUES ('11', 'Celtic', 'Concarneau');

INSERT INTO FILMS_SALLES VALUES ('1', '4');
INSERT INTO FILMS_SALLES VALUES ('2', '1');
INSERT INTO FILMS_SALLES VALUES ('3', '11');
INSERT INTO FILMS_SALLES VALUES ('6', '6');
INSERT INTO FILMS_SALLES VALUES ('6', '12');
INSERT INTO FILMS_SALLES VALUES ('6', '7');
INSERT INTO FILMS_SALLES VALUES ('7', '13');
INSERT INTO FILMS_SALLES VALUES ('7', '8');
INSERT INTO FILMS_SALLES VALUES ('8', '2');
INSERT INTO FILMS_SALLES VALUES ('9', '6');
INSERT INTO FILMS_SALLES VALUES ('9', '12');
INSERT INTO FILMS_SALLES VALUES ('10', '13');
INSERT INTO FILMS_SALLES VALUES ('10', '5');
INSERT INTO FILMS_SALLES VALUES ('10', '11');
INSERT INTO FILMS_SALLES VALUES ('11', '3');
		   